//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShopApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string TitleOfBooks { get; set; }
        public string Authors { get; set; }
        public Nullable<int> PublicationYear { get; set; }
        public Nullable<int> price { get; set; }
    }
}
